---
- name: Ensure we have latest Perl toolchain
  apt:
    name:
      - perl
      - perl-doc
      - cpanminus
      - carton
      - liblocal-lib-perl
    state: latest
  become: yes

- name: Ensure we have latest Rakudo toolchain
  apt:
    name: rakudo
    state: latest
  become: yes

- name: Ensure we have latest OCaml toolchain
  apt:
    name: opam
    state: latest
  become: yes

- name: Ensure we have latest Node.js toolchain
  apt:
    name:
      - nodejs
      - npm
    state: latest
  become: yes

- name: Ensure we have latest Python toolchain
  apt:
    name:
      - python3-pip
      - pipenv
    state: latest
  become: yes

- name: Ensure system default Python is Python 3
  become: yes
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3

- name: Ensure system default Pip is Pip 3
  become: yes
  alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3

- name: Ensure system default PyDoc is PyDoc 3
  become: yes
  alternatives:
    name: pydoc
    link: /usr/bin/pydoc
    path: /usr/bin/pydoc3

- name: Ensure system default Python virtualenv is the latest
  become: yes
  apt:
    name: python3-venv
    state: latest
